config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      put 'join_game'
      put 'next_player_turn'
      post 'add_disk_to_game'
    end
    collection do
      get 'play_game'
    end
  end

  get 'disks/:id/' => 'disks#show'

  root to: 'application#redirect_to_game_page'

end

app/models/disk.rb
class Disk < ActiveRecord::Base
  belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :disks

  enum state: {
    WAITING_FOR_OPPONENT: 0,
    IN_PROGRESS: 1
  }

  enum whose_turn: {
    PLAYER_ONE_TURN: 1,
    PLAYER_TWO_TURN: 2
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def redirect_to_game_page
    redirect_to play_game_games_url
  end
end

app/controllers/disks_controller.rb
class DisksController < ApplicationController
  before_action :set_disk, only: [:show]

  def show
    respond_to do |format|
      if @disk.present?
        format.json { render json: @disk.to_json }
      else
        #TODO
      end
    end
  end

  private

  def set_disk
    @disk = Disk.find(params[:id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_game, only: [:show, :edit, :update, :destroy, :join_game, :next_player_turn, :add_disk_to_game]

  def play_game
    respond_to do |format|
      format.html { render :game_page }
    end
  end

  def join_game
    respond_to do |format|
      if @game.present?
        if @game.players_connected == 1
          @game.players_connected += 1
          @game.state = Game.states[:IN_PROGRESS]
          @game.save!
          format.json { render json: @game.to_json }
        end
      else
        # TODO
      end
    end
  end

  def next_player_turn
    respond_to do |format|
      if @game.present?
        if @game.PLAYER_ONE_TURN?
          @game.update_attribute(:whose_turn, Game.whose_turns[:PLAYER_TWO_TURN])
        else
          @game.update_attribute(:whose_turn, Game.whose_turns[:PLAYER_ONE_TURN])
        end
        format.json { render json: @game.to_json }
      else
        # TODO
      end
    end
  end

  def add_disk_to_game
    permitted_disk_params = disk_params
    @disk = Disk.new(permitted_disk_params)

    respond_to do |format|
      if @game.present?
        if @disk.save!
          @game.update_attribute(:last_added_disk_id, @disk.id)
          format.json { render json: @disk.to_json }
        else
        end
      else
        #TODO
      end
    end
  end

  def index
    @games = Game.all
  end

  def show
    respond_to do |format|
      format.json { render json: @game.to_json }
    end
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    permitted_params = game_params
    permitted_params[:state] = permitted_params[:state].to_i
    permitted_params[:whose_turn] = permitted_params[:whose_turn].to_i
    @game = Game.new(permitted_params)

    respond_to do |format|
      if @game.save
        format.html { render :show, status: :created, location: @game }
        format.json { render json: @game.to_json }
      else
        format.json { render json: @game.to_json, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:state, :whose_turn, :last_added_disk_id, :players_connected)
  end

  def disk_params
    params.require(:disk).permit(:game_id, :row, :column, :player, :winning_disk)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/game_page.html.erb
<button id="pause-button" hidden="true">Pause</button>
<button id="reset-button" onclick="resetGame();" hidden="true">Reset</button>
<span id="game-status">Player 1 Turn</span>
<button id="new-game-button">New Game</button>
<button id="join-game-button">Join Game</button>
<input id="game-id-to-join" type="text" placeholder="game id"></input>
<span id="your-game-id">Your game id: </span>
<br><br>
<button class="add-disk-button" id="add-disk-col1" onclick="addDisk(1);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col2" onclick="addDisk(2);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col3" onclick="addDisk(3);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col4" onclick="addDisk(4);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col5" onclick="addDisk(5);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col6" onclick="addDisk(6);">Add Disk</button>
<button class="add-disk-button" id="add-disk-col7" onclick="addDisk(7);">Add Disk</button>
<div>
  <canvas id="game-area" width="700" height="600"></canvas>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Game State:
  <%= @game.state %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CFour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'c4js', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-2.1.4.min', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>